layout_spectrum: 0.7163959
typography_spectrum: 0.8537957
color:
  saturation: 0.8071996
  lightness: 0.2182388
  brandStrength: 0.303952
  rhythmicContrast: 0.3945777
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Amazing God
